name: 'jaffle_shop'
version: '1.0'
config-version: 2

profile: 'jaffle_shop'

model-paths: ["models"]
# analysis-paths: ["analysis"]
# test-paths: ["tests"]
# seed-paths: ["seeds"]
# macro-paths: ["macros"]

# target-path: "target"
# clean-targets: ["target", "dbt_packages"]

models:
  jaffle_shop:
    examples:
      +materialized: view
    staging:
      +materialized: table
      +schema: staging
    analytics:
      +materialized: table
    
